AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  UserPoolName:
    Type: String
  AWSStackName:
    Type: String

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      UserPoolName: !Ref UserPoolName

  UserPoolTokenClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - USER_PASSWORD_AUTH

Outputs:
  UserPoolId:
    Description: 'Cognito User Pool ID'
    Value:
      Ref: UserPool
    Export:
      Name: !Sub '${AWSStackName}-user-pool-id'

  UserPoolClientId:
    Description: 'Cognito User Pool Client ID'
    Value:
      Ref: UserPoolTokenClient
    Export:
      Name: !Sub '${AWSStackName}-user-pool-client-id'

  UserPoolArnParam:
    Description: 'Cognito User Pool'
    Value: !GetAtt 'UserPool.Arn'
